스크랩함 기능 생성
DevKor-github/KUDOG-back pull request #10
Opened 2024-04-01 10:55 UTC by leestar0629

feat1:유저별 스크랩함 조회
feat2:유저별 스크랩함 생성(이름으로)
feat3:유저별 스크랩함 수정(이름으로)
feat4:유저별 스크랩함 삭제
테스트를 하는 방법을 몰라서
response dto 추가 못함

2024-04-02 16:08 UTC, acvxx commented on src/scrap/scrap.controller.ts
@UseGuards(AuthGuard('jwt-access')) 데코레이터를 사용하여 사용자들을 인증해주고 있으니 userId의 값을 따로 전달받지 않고 req.user.id로 값을 전해주면 좋을 것 같아요!
기존에 있던 controller 코드 참고하면 조금 더 쉬우실 거예요 😄

2024-04-02 16:08 UTC, acvxx commented on src/scrap/scrap.service.ts
> +  async updateScrapBox(scrapBoxId: number, newName: string) {
update나 delete를 진행하기 전에 소유하고 있는 user가 맞는지 검증하는 과정이 있으면 좋을 것 같아요!

2024-04-03 02:21 UTC, overthestream requested changes

2024-04-03 02:21 UTC, overthestream commented on src/scrap/dtos/scrapbox.dto.ts
> +  userId: number;
userId는 필요 없어도 될 것 같습니다

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +  @Post('/box/byname')
path가 /box 만 되어도 괜찮을 것 같아용

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +    description: '스크랩박스 정보,스크랩박스 아이디',
스크랩 박스 정보만 .!

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +  @ApiResponse({
Api CreatedResponse가 맞을 것 같아용

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +    @Body('userId') userId: number,
request를 받아서 Req.user.id로 처리하면 됩니당 경아님의 리뷰도 참고해주세용

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +    @Body('boxName') boxName: string,
개인적으로는 
```typescript
@Body() body: ScrapBoxDto
```
로 받아서 body.boxName 으로 처리하는게 더 낫지 않을까 싶어용

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +  })
Promise<void> 같은 리턴 타입을 명시해주세용

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +  @Get('/box/:userId/byname')
여기도 path는 /box 만 해도 될 것 같아요

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +  @ApiResponse({ description: '조회 성공' })
ApiOkResponse!

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.service.ts
> +        throw new BadRequestException('해당 이름의 scrapbox는 존재합니다');
이름 중복 처리는 안해줘도 될 것 같아요

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.service.ts
> +  async createScrapBox(userId: number, name: string) {
각 함수에 return type을 명시합시다

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.service.ts
> +      if (!scrapBoxes)
이 exception은 업성도 될 것 같아요ㅕㅇ

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.service.ts
> +      throw new BadRequestException('ScrapBox를 조회하는 것을 실패하였습니다');
이런 건 500으로 하는 게 어떨까요?

2024-04-03 02:21 UTC, overthestream commented on src/scrap/scrap.controller.ts
> +  @Put('/box/:scrapBoxId/rename')
/box/:scrapBoxId 만 해도 괜찮을 것 같아용

2024-04-04 08:58 UTC, overthestream approved these changes

2024-04-04 09:30 UTC, acvxx approved these changes
Swagger 관련 코드들 따로 빼니까 컨트롤러 파일 가독성이 좋아졋어요! 👍

2024-04-04 09:36 UTC, merged