Alarm
DevKor-github/KUDOG-back pull request #21
Opened 2024-04-08 04:31 UTC by overthestream

2024-04-08 06:59 UTC, overthestream commented on src/users/users.module.ts
> +  imports: [TypeOrmModule.forFeature([KudogUser]), NotificationModule],
app.module.ts에 추가해주세요!

2024-04-08 06:59 UTC, overthestream commented on src/entities/notification.entity.ts
> +  @JoinColumn({ name: 'notification_token_id', referencedColumnName: 'id' })
이거는 User를 참조하도록 해두면 더 좋을 것 같아요!

2024-04-08 06:59 UTC, overthestream commented on src/entities/notification.entity.ts
> +  body: any;
body?:string 으로 하면 됩니다!

2024-04-08 06:59 UTC, overthestream commented on src/entities/notification.entity.ts
> +  created_By: number; // 알림을 생성한 사용자의 ID
status랑 created_by 대신 알림이 생성된 일자를 표시하는 column을 추가하면 더 좋을 것 같아요

2024-04-08 06:59 UTC, overthestream commented on src/notification/notification.controller.ts
> +  @Get(':userId')
이거 대신 UseGuard()를 사용하고, @User를 이용해서 userId에 접근할 수 있어요 ! scrap 폴더 안의 파일들을 참조하면 더 쉬울 것 같습니다 ㅎㅎ

2024-04-08 06:59 UTC, overthestream commented on src/notification/notification.controller.ts
> +  async getNotifications(@Param('userId') userId: number) {
여기 response type 명시도 추가해주면 더 좋을 것 같네요

2024-04-08 06:59 UTC, overthestream commented on src/notification/notification.service.ts
> +firebase.initializeApp({
얘는 constructor 안에 넣어주면 더 좋을 것 같아요

2024-04-11 09:28 UTC, hyp3rflow requested changes

2024-04-11 09:28 UTC, hyp3rflow commented on src/decorators/page.decorator.ts
> +    const request = cts.switchToHttp().getRequest();
request의 type이 any인가요? 아래의 property chaining이 에러를 낼 가능성이 있어보여요.

2024-04-11 09:28 UTC, hyp3rflow commented on src/decorators/page.decorator.ts
> +    const request = cts.switchToHttp().getRequest();
type을 정확하게 알고 있다면 getRequest의 제너릭을 채우면 될 것 같네요.

2024-04-11 09:28 UTC, hyp3rflow commented on src/entities/notification-token.entity.ts
> +  is_active: boolean;
여기만 케이스가 다른 이유가 있나요?

2024-04-11 09:28 UTC, hyp3rflow commented on src/notification/notification.service.ts
> +    const firebase_key = {
얘만 케이스가 다른 것 같네요

2024-04-11 09:28 UTC, hyp3rflow commented on src/notification/notification.service.ts
> +        userId: userId,
```suggestion
        userId,
```

2024-04-11 09:28 UTC, hyp3rflow commented on src/notification/notification.service.ts
> +          }
```suggestion
          if (response.error.code === 'messaging/invalid-registration-token') {
            return this.deleteToken(userIds[index], tokenList[index]);
          }
          if (response.error.code === 'messaging/registration-token-not-registered') {
            return this.deleteToken(userIds[index], tokenList[index]);
          }
          if (response.error.code === 'messaging/server-unavailable') {
            try {
              return firebase.messaging().send({
                notification: {
                  title,
                  body,
                },
                token: tokenList[index],
              });
            } catch (err) {
              throw new InternalServerErrorException(err);
            }
          }
          throw new InternalServerErrorException(response.error);
```
이거 반영안하더라도 2번째 else if가 assignment로 되어있는건 꼭 수정해주세요

2024-04-11 09:32 UTC, overthestream commented on src/decorators/page.decorator.ts
> +    const request = cts.switchToHttp().getRequest();
Request type은 Express.Request고 query object는 반드시 존재하는 것으로 알고있는데 타입명시 해주는게 좋을까요?

2024-04-11 09:33 UTC, overthestream commented on src/entities/notification-token.entity.ts
> +  is_active: boolean;
다른 사람 코드를 수정하다보니 그만

2024-04-11 09:33 UTC, overthestream commented on src/notification/notification.service.ts
> +          }
아.

2024-04-11 13:25 UTC, BeLeap commented on src/entities/kudogUser.entity.ts
> +  notificationTokens: NotificationToken[];
이건 뭔가요? 되게 Notification이랑 1 to 1 관계일 것처럼 생겼는데요

2024-04-11 13:25 UTC, BeLeap commented on src/entities/notification-token.entity.ts
> +    onDelete: 'CASCADE',
onDelete면 실제로 데이터를 지우는 경우가 있나보네요? 실제로 데이터를 지우는 것보단 disabled같은 flag를 통해서 안보이게 처리하고 개인정보 같은 것만 비식별화하게 처리하는 것이 더 좋지 않을까하는 생각이 드네요.

2024-04-11 13:25 UTC, BeLeap commented on src/notification/dtos/noticiationInfoResponse.dto.ts
> +  date: string;
요거는 개인적인 취향이긴한데...저는 컴퓨터에 있는 데이터는 모두 Computational해야한다고 생각하거든요. String보다는 Unix Timestamp를 활용하여 데이터를 주고 받고 보여주는 View에서만 변환하여 보여주는 것이 처리하기에 더 편할 것 같습니다.

2024-04-11 13:25 UTC, BeLeap commented on src/notification/notification.controller.ts
> +    return await this.notificationService.getNotifications(user.id, pageQuery);
return에 await거시면 async context가 하나 더 생겨서 느려지는 것으로 알고 있습니다.

2024-04-11 13:25 UTC, BeLeap commented on src/notification/notification.service.ts
> +      Promise.all(
여기 await 있어야 될 거 같이 생겼는데 없어도 되나여

2024-04-11 16:26 UTC, BeLeap commented on src/notification/notification.service.ts
> +      token: token,
```suggestion
       token,
```

이거 아마 linter 있을걸요?

2024-04-11 16:27 UTC, overthestream commented on src/entities/kudogUser.entity.ts
> +  notificationTokens: NotificationToken[];
유저의 기기별 firebase messaging 토큰을 저장하는 테이블입니당

2024-04-11 16:27 UTC, BeLeap commented on src/notification/notification.controller.ts
> +    return await this.notificationService.getNotifications(user.id, pageQuery);
아니라네요 ㅎㅎ

2024-04-11 16:27 UTC, overthestream commented on src/notification/notification.controller.ts
> +    return await this.notificationService.getNotifications(user.id, pageQuery);
저도 그렇게 알고 있었는데 바뀌엇더라구요 ~

2024-04-11 16:31 UTC, overthestream commented on src/notification/notification.service.ts
> +      Promise.all(
푸시 알림을 보내는 함수가 굳이 전송 끝날 때까지 기다릴 이유가 없을 것 같아서 await를 안넣었습니다

2024-04-11 16:31 UTC, BeLeap commented on src/notification/notification.controller.ts
> +    return await this.notificationService.getNotifications(user.id, pageQuery);
맞다는데요? ㅋㅋ

2024-04-11 16:32 UTC, BeLeap commented on src/notification/notification.service.ts
> +      Promise.all(
어 그럼 이거 실행 안끊기나요 모르겠네

2024-04-11 16:34 UTC, overthestream commented on src/entities/notification-token.entity.ts
> +    onDelete: 'CASCADE',
앱스토어 약관에 개인정보 삭제 약관 같은 것들이 복잡하게 있어서 그냥 싹 다 지우게 만들어뒀었습니다 ㅠ

2024-04-11 16:37 UTC, BeLeap commented on src/entities/notification-token.entity.ts
> +    onDelete: 'CASCADE',
아하 ㅠㅠ 그거 개인정보 분리보관 의무도 없어졌을텐데 아직 업뎃이 안됐나...

2024-04-11 16:37 UTC, BeLeap commented on src/entities/notification-token.entity.ts
> +    onDelete: 'CASCADE',
근데 개인정보 비식별화만 해도 상관없긴해요 보통은...

2024-04-11 17:01 UTC, BeLeap commented on src/notification/notification.service.ts
> +      Promise.all(
<img width="629" alt="2024-04-12_1 43 02" src="https://github.com/DevKor-github/KUDOG-back/assets/46488521/d53a87d7-1806-4506-b272-96d5fe2a3630">
안끊기네요

2024-04-12 04:07 UTC, merged