Feat: subscribe
DevKor-github/KUDOG-back pull request #22
Opened 2024-04-08 14:27 UTC by acvxx

## PR 포함 사항
- 구독함 생성, 삭제, 수정, 조회 및 구독함 세부 정보 조회
- 구독함 세부 정보 조회는 날짜별 notice를 가져오기 위해 날짜 정보를 필수로 입력해야 함.

## TODO
- 조인이 너무 많이 일어나서 코드/entity 리팩토링 필요
- 여러 논의사항 함께 논의 후 코드 수정 필요

## 논의사항
- 구독함 정보를 가져올 때 조인이 너무 많이 일어남
- 구독함 생성/수정 시 모든 작업이 끝나고 마지막에 다시 한번 조회하여 값을 반환하고 있는데 괜찮을지? (여러 테이블을 조인하여 조회하기 위해 다시 한번 조회했음)
- 구독함 수정 시 현재 구독 중인 카테고리와 비교하여 삭제 및 삽입을 해주고 있는데 모두 다 지우고 다 넣는 게 cost가 덜 들지 고민

## Test

2024-04-08 16:47 UTC, overthestream requested changes

2024-04-08 16:47 UTC, overthestream commented on src/subscribe/dtos/subscribeBoxResponse.dto.ts
> +  static entityToDto(entity: SubscribeBox): SubscribeBoxResponseDto {
일단 리팩토링할때 static 함수를 만들었긴 한데, 그냥 constructor를 만드는 게 나을까요? 의견 주세용

2024-04-08 16:47 UTC, overthestream commented on src/subscribe/dtos/subscribeBoxResponseWithNotices.dto.ts
> +  static toDto(
왜냐면 부모 클래스랑 같은 기능을 하는 함수인데 override가 안돼서 이렇게 이름 바꿔서 쓰는게 좀 싫네요 
to DTO라는게 그냥 constructor랑 같은 기능을 하는 거기도 하고.

2024-04-08 16:47 UTC, overthestream commented on src/subscribe/subscribe.controller.ts
> +      1, //user.id,
이거 안고쳐쓰 ㅋㅋ

2024-04-08 16:47 UTC, overthestream commented on src/subscribe/subscribe.service.ts
> +    await this.categoryPerSubscribeBoxRepository.save(subscriptions);
이거 SELECT 쿼리를 줄이려면, exception handling으로구현하면 될 것 같아요.
지금, tuple(box_id(FK), category_id(FK)) 가 PK인 상황이니, 
중복된 튜플은 DB에 생성되지 않고, category_id가 맞지 않아도 exception이 발생하여 insert가 실패하니까요.
try catch로 감싸주면서 orm exception 핸들링하는식으로 하면, 쿼리를 줄일 수 있지 않을까 싶습니다.

2024-04-08 16:47 UTC, overthestream commented on src/subscribe/subscribe.service.ts
> +      return SubscribeBoxResponseDto.entityToDto(subscribeBox);
```ts
=> {
    return SubscribeBoxResponseDto.entityToDto(subscribeBox);
}
```
대신 간단하게
``` ts
=> SubscribeBoxResponseDto.entityToDto(subscribeBox);
```
로 하는 게 나을까요?

2024-04-08 16:47 UTC, overthestream commented on src/subscribe/subscribe.service.ts
> +    const categoriesToDelete: CategoryPerSubscribeBoxEntity[] =
이것도 비슷한 방법으로 삭제가능할듯?

2024-04-09 07:55 UTC, acvxx commented on src/subscribe/dtos/subscribeBoxResponseWithNotices.dto.ts
> +  static toDto(
음 적용할 만한 패턴들도 한번 찾아보고 논의해볼까여? 이것도 공부하면 꽤 도움이 될 것 같은데!!!

2024-04-09 08:23 UTC, overthestream commented on src/subscribe/dtos/subscribeBoxResponseWithNotices.dto.ts
> +  static toDto(
좋습니다 ! ㅎㅎ 생성자나 builder pattern 어떨까 시펑용

2024-04-09 09:10 UTC, acvxx commented on src/subscribe/subscribe.service.ts
> +    await this.categoryPerSubscribeBoxRepository.save(subscriptions);
- exception이 발생하면 모든 튜플이 생성되지 않는 문제로 기존 코드 유지

2024-04-10 08:44 UTC, overthestream approved these changes

2024-04-10 08:44 UTC, merged