Feat/lee 마이페이지 알림 수신 시간 변경(구독함 전체)
DevKor-github/KUDOG-back pull request #27
Opened 2024-05-05 03:41 UTC by leestar0629

2024-05-09 11:02 UTC, overthestream requested changes
푸시알림은 notification domain에 만들어뒀으니 확인해보십쇼

2024-05-09 11:02 UTC, overthestream commented on src/users/users.controller.ts
> +    @Param('sendTime') sendTime: string,
Body로 받아주세요

2024-05-09 11:02 UTC, overthestream commented on src/users/users.controller.ts
> +  ):Promise<void>{
prettier formatter 설정해주세용

2024-05-09 11:02 UTC, overthestream commented on src/users/users.service.ts
> +    await this.userRepository.save(user);
이거 save 하려면 cascade 설정 해줘야댑니다요

2024-05-10 06:18 UTC, acvxx commented on src/users/users.controller.ts
> +    @Param('sendTime') sendTime: string,
Body로 받고, DTO 만들어서 sendTime에 대한 input validation 할 수 있게 DTO로 만들면 좋을 것 같아요! 

DTO로 input validation 만드는 건 NoticeFilterRequestDto에 start_date나 end_date 참고하면 좋을 것 같고
Body로 받는 부분은 notification.controller.ts 부분에 tokenRequest 참고해보세요!

2024-05-21 05:40 UTC, closed without merging